// Generated by `mise run generate-skill` from skills/jev-sim-use. Do not edit.

extension SkillBundle {
    /// Every file of skills/jev-sim-use, by its path inside the skill directory; SKILL.md comes first.
    static let files: [(path: String, contents: String)] = [
        (
            "SKILL.md",
            #####"""
            ---
            name: jev-sim-use
            description: Reach a screen, setting, or filled-in form in an iOS Simulator or Android app with one command instead of driving sim-use tap by tap. Use it whenever an agent needs to navigate an app to some state before checking or testing something there ("open Settings > Display", "search for ramen and show the results", "sign in with this email", "create a memo and save it"), even if the user only says "go to", "open", or "get to". jev-sim-use hands each step to Jev, a fast typed-judgment model, so navigation costs one shell call rather than one reasoning turn per tap. Also runs any sim-use command through `jev-sim-use exec`.
            ---

            # jev-sim-use

            Delegate navigation and keep your own turns for the real work. You give one goal; jev-sim-use reads the screen with
            sim-use, asks Jev which on-screen action comes next, acts, and repeats until Jev judges the goal reached or has to
            stop. Jev is fast and good at picking a visible target. It does not know your app, cannot write text, and can be
            wrong about being done, so your part is to give it an unambiguous goal, check the end state, and fill in facts when
            it stops.

            ## When to use it

            - `jev-sim-use "<goal>"` to get somewhere in several steps: a screen, a toggle state, a submitted search, a saved
              item.
            - sim-use itself for reading the screen, checking a result, single exact actions, and anything Jev is not offered.
              Run it through `jev-sim-use exec <sim-use args>` to target the same device. Learn its commands from sim-use's own
              skill and `sim-use --help`; [references/sim-use.md](references/sim-use.md) says how to install that skill.

            ## Before the first run

            ```sh
            jev-sim-use doctor     # sim-use installed, one usable device, TYPESAFE_API_KEY set
            ```

            - Open the app yourself; sim-use cannot launch apps. Give it a few seconds, then dismiss any late prompt (rating
              request, tracking, notifications, password save). These appear after launch and derail a run midway.
            - When several devices are booted, pass `--device <deviceId>` to every command, including `exec`, so every step
              and every check hits the same device.
            - Give the simulator what the app needs from the device. An app that records location or motion does nothing
              useful on a simulator with no location set; set one (and a moving route when the task needs movement) with
              `xcrun simctl location`, as its `--help` describes.
            - Typing pastes through the simulator's hardware keyboard. Without one connected, the run stops with a setup error
              (exit 2) instead of silently typing nothing.

            ## Choose the goal's form: an end state or numbered steps

            The goal is the only thing Jev knows about your intent. Jev does not know the app, so every screen it has to find
            on its own is a place where it can guess wrong or hand over. Choose the form by how much of the route Jev would
            have to discover:

            - **An end state** for short goals: one to three actions, where the target is on the current screen or one obvious
              hop away. Describe the finished state in the app's own terms.
            - **Numbered steps** for anything longer: several screens, a flow that returns somewhere and continues, or a screen
              with two features that look alike. Spell out the route, one action per step. In a comparison run, a
              create-edit-favourite-convert-complete flow written as an end state stalled at its fourth action and once left the
              app; the same flow written as numbered steps ran 15 actions in about a minute, most of them at 0.8 support or
              higher.

            <examples>
            <example>
            jev-sim-use "Turn on Dark Mode in Settings"
            </example>
            <example>
            jev-sim-use "Search the memos for the query text and show the results" -t query=milk
            </example>
            <example>
            jev-sim-use --max-steps 30 "1. On the Home tab, tap the New Memo button.
            2. In the editor, enter the title text into the Title field.
            3. Tap Save.
            4. In the memo list, tap the memo titled with the title text.
            5. On the memo's screen, tap Favorite.
            6. Tap Type and choose To-do.
            7. Tap Back until the Home tab shows the memo list.
            The goal is reached when the memo shows as a favorite to-do in the Home tab's list." -t title="Buy milk"
            </example>
            <example>
            jev-sim-use "1. Tap the Profile tab.
            2. Tap Account, then Sign In.
            3. Enter the email into the Email field and the password into the Password field.
            4. Tap Sign In.
            The goal is reached when the Profile tab shows the signed-in email." -t email=alice@example.com -t password=hunter2
            </example>
            </examples>

            How to write numbered steps so Jev follows them:

            - Read the screens first (with sim-use through `exec`) and use each control's label exactly as the screen shows it.
              Jev matches steps against those labels, so "tap Favorite" beats "mark it as a favourite" when the button says
              Favorite.
            - Say which screen each step happens on ("On the Home tab", "In the editor"). That keeps Jev from acting on a
              look-alike control on the wrong screen.
            - Refer to controls by their labels, never by coordinates or positions; Jev only sees labels.
            - Make an explicit save or submit tap its own step when the app has one.
            - End with the finished state as a sentence Jev can check on screen. Exit 0 is still a claim; read the screen.
            - Give the run room: allow about two actions per numbered step with `--max-steps` (the default is 15).

            These apply to both forms:

            - Pass every string to type as `-t name=value`. Jev never writes text; it sees only the name and picks the field whose
              label fits, so name strings by what they are (`email`, `password`, `query`, `title`). Values never leave the
              machine. After typing, elements that show a text carry its name, so "the memo titled with the title text" is
              findable.
            - When the goal creates something through a form with a save or submit button, say "and save it" (or give Save its
              own step). Typed text in an open form is not saved, and Jev does not count it as done. When the app saves by itself
              (stopping a recording, toggling a setting), describe the finished state instead ("the recording is stopped and
              listed in history"); a "save" step that does not exist leaves Jev looking for one and handing over.
            - Name the feature when two look alike ("edit it yourself" versus "ask the AI assistant"). An AI feature may
              otherwise receive your text as an instruction.
            - Place words such as "home", "settings", "search", and "back" mean the app's own tab, screen, or button first; the
              device's only when the app has none. Say "the device's Home Screen" if you do mean to leave the app, and expect a
              hand-over: leaving the app needs high confidence because sim-use cannot open it again.
            - When a long flow still stops, verify the screen it stopped on, `tell` what is missing, and `resume`. When the flow
              has natural checkpoints you want to verify anyway (a record that must exist before it can be analysed), run each
              part as its own goal.

            ## Read the result, then verify it

            stdout is the outcome line; stderr shows each step. When the goal was not reached, `Session: <id>` follows.

            | Exit | Meaning | What to do |
            |---|---|---|
            | 0 | Goal reached | Read the screen and verify before relying on it |
            | 1 | Stopped before the goal | Read the reason below, then supervise the session |
            | 2 | Setup problem | Run `jev-sim-use doctor` and fix what it reports |
            | 3 | sim-use or Jev failed mid-run | Read the screen first (the failed step may have scrolled or moved it), then retry once; if it repeats, read the error |

            Exit 0 is Jev's judgment, not proof. Read the screen once the app has settled: a saved item can take a second or two
            to show up in a list, so read, wait about two seconds, and judge the second reading.

            Stop reasons on exit 1:

            - **confidence below the threshold**: Jev was unsure what to do next and handed over instead of guessing. The step
              line shows which answer was weak, such as `support 0.49 [operation 0.97, element 0.49]`: here, what to act on.
            - **no offered action advances the goal**: Jev does not know where the target lives. `tell` where it is, or get
              closer with `exec`, then `resume`.
            - **the screen stopped changing**: actions are not landing. Read the screen and look at it before resuming.
            - **the goal is probably reached, but not surely**: read the screen; if it is not done, `tell` what the finished
              screen looks like and `resume`.
            - **step limit reached**: `resume` gives another `--max-steps` actions.
            - **app crashed or disappeared**: relaunch the app before resuming.

            When a stop is not obvious, read [references/troubleshooting.md](references/troubleshooting.md): it maps the usual
            causes (rows exposed as loose text, look-alike buttons, unlabelled sliders, prompts sim-use cannot see, slow
            submits) to the note or fix that resolves each.

            ## Supervise the session instead of starting over

            Every run is a session that keeps the goal, the history, and your notes. When it stops short, look, add what Jev
            cannot know, and continue; a fresh run with a longer goal loses all of that.

            ```sh
            jev-sim-use session show                  # goal, notes, how each run ended, every action taken
            jev-sim-use session tell -n "Dark Mode is the Dark Appearance switch under Developer"
            jev-sim-use session tell -n "The goal is reached when the Dark Appearance switch is on"
            jev-sim-use session forget -n 1           # drop note 1 (as `show` numbers them) if it proved wrong
            jev-sim-use session resume                # same goal, notes, and history; exits like a run
            ```

            - Write notes as facts about the app: where a setting lives, what a label means, what the finished screen looks
              like. Jev reads every note for every action, so a tap instruction in a note keeps pulling it back to that tap
              after it is done. The route belongs in the goal's numbered steps; notes supply the facts the steps rely on.
            - Remove a wrong note with `forget`; a correction added on top still leaves the wrong fact in front of Jev.
            - Look at the screen it stopped on (read it with sim-use through `exec`) before adding a note.
            - Prefer `tell` and `resume` to acting by hand, so the session keeps a record of what worked. Act by hand with sim-use
              through `exec` for what Jev is not offered or what fails the same way twice (see the tool-limits lesson in
              [references/lessons.md](references/lessons.md)); `resume` starts from whatever screen is showing.
            - Add the missing fact rather than lowering `--min-confidence`. A lowered bar once let a run leave the app and report
              success in another one; a hand-over only costs a note.
            - Commands take a session id; without one they use the most recent session. `session list` shows them all.

            Sessions live under `$XDG_STATE_HOME/jev-sim-use/sessions` (default `~/.local/state`). Reaching the goal deletes the
            session; an unfinished one expires a week after it last changed.

            ## What Jev can do

            Taps; long-press, swipes, pinch, and rotate on an element; scrolls in four directions; going back where the screen
            has a back button (iOS) or always (Android); a right-edge swipe; Return, to submit a search or form; and hardware
            buttons. Tapping a Delete control needs at least 0.6 confidence and a hardware button (leaving the app) 0.85,
            because going back cannot undo them. Anything else sim-use can do is left to you through `exec`.

            ## Options

            | Option | Default | Use |
            |---|---|---|
            | `-t, --text` | none | `name=value` to enter into a field; Jev sees only the name |
            | `-d, --device` | the only usable device | A sim-use device id (list them with sim-use through `exec`) |
            | `--max-steps` | 15 | Upper bound on actions in this run; `session resume` gets a fresh budget |
            | `--min-confidence` | 0.55 | Lower it to hand over less often, raise it to be more careful |
            | `--actions` | all | Comma-separated operation groups Jev may choose from (`tap`, `type`, `scroll`, `back`, `return`, `long-press`, `swipe`, `pinch`, `rotate`, `buttons`). Naming only what the goal needs, such as `tap,type,scroll,back` for form and navigation flows, shortens every request and rules out wrong gestures and hardware buttons |

            ## Privacy

            Each step sends the screen's visible labels and values, the goal, the action history, the session notes, and the
            names of the `-t` texts to the Jev endpoint; `-t` values never leave the machine. Unfinished sessions are kept
            locally for up to a week, readable only by the user, with the goal, texts, notes, and actions. Do not run it on
            screens with data that may not leave the machine.

            ## More

            - [references/sim-use.md](references/sim-use.md): install sim-use's own skill; read before using sim-use directly.
            - [references/troubleshooting.md](references/troubleshooting.md): read when a run stops and the reason is not obvious.
            - [references/lessons.md](references/lessons.md): what driving real apps taught about goals, verification, and app
              accessibility; read before planning a long or unfamiliar flow.

            """#####,
        ),
        (
            "references/lessons.md",
            #####"""
            # Lessons from driving real apps with jev-sim-use

            These come from running the same goals round after round against several third-party iOS apps and classifying every
            failure. They apply to agent-driven UI work generally, not only to this tool.

            ## Success is a claim until the screen proves it

            Exit 0 means Jev judged the goal reached. Twice that judgment was wrong: once on a detail screen inside the tab it
            was asked to return to, once after a run wandered into another app and finished a same-named item there. Check the
            end state by reading the screen before building on it, and read it after the app settles: a saved item can take a second
            or two to appear in a list, so read, wait about two seconds, and judge the second reading.

            ## Ambiguity causes more wrong successes than weak judgment

            Every wrong success traced back to a goal that allowed two readings: "home" (the app's tab or the device's Home
            Screen), "edit" (the editor or an AI assistant), "post a record" (open the item or add a new one). Jev resolves
            ambiguity plausibly, not necessarily as you meant. Name the end state in the app's own terms, and say which feature
            when two look alike.

            ## A hand-over is cheap; a wrong action is not

            Lowering `--min-confidence` to push a stuck run through once let it press the Home button, leave the app, and report
            success in another app. Scrolls and back cost a step when wrong; a tap on the wrong control or leaving the app can
            cost the whole run, or change data. When a run stops, add the missing fact with `tell` rather than lowering the bar.

            ## The app's accessibility bounds what any agent can do

            Most of the stubborn failures were not the model's: tappable rows exposed as loose text, images labelled with asset
            names, sliders labelled with their raw position, look-alike buttons without hints. Screen-reader users hit the same
            walls. Fixing the app (one element per tappable row, a button trait, real labels, values with units, hints for
            look-alike controls) helped both, and removed failures that no prompt wording could.

            ## Spell out long routes; do not make the agent discover them

            Uncertainty compounds: ten steps at 90% each succeed about a third of the time. A flow such as create, edit,
            favourite, convert, and complete, written as an end state, stalled at a different step on each attempt. The same flow
            written as numbered steps with the screens' own labels ran through in about a minute with high support at almost
            every step: each step left one obvious choice instead of a search. When a flow is long, give the route; when it has
            checkpoints worth verifying, also run it as a few goals and check each end state before starting the next.

            ## Recognise tool limits quickly

            Some things sim-use cannot do on a simulator: drag a SwiftUI slider, see a prompt drawn by another process, read most
            cells of a colour grid, or trust an instant tap on every control. When the same action fails the same way twice,
            treat it as a limit: do that step by hand or with a coordinate tap, then continue. Retrying variations wastes the
            most time of anything.

            ## Check whether the data allows what you expect to see

            An option or screen that a goal expects can be absent for a reason in the data, not in the tool: a colouring by
            altitude appeared only for records with altitude changes, which a simulated route never has. When the expected UI is
            missing, look at what the app needs to show it before retrying or blaming the agent.

            ## Set up the start state deliberately

            Runs are only comparable when they start from the same screen with the same data. Launch the app, wait a few
            seconds, clear late prompts, and remove data left by earlier runs. Provide what the app reads from the device, such as
            a simulated location or route for apps that record movement. Launching through `simctl` does not pass the
            environment an Xcode scheme sets (debug tokens, test credentials); pass it with `SIMCTL_CHILD_<NAME>=…`.

            ## Keep test data traceable

            Use a staging backend and throwaway addresses (`…@example.com`) for sign-up flows, and write down every account
            created so it can be removed later. Never exercise sign-up or purchase flows against production.

            """#####,
        ),
        (
            "references/sim-use.md",
            #####"""
            # Using sim-use alongside jev-sim-use

            jev-sim-use drives the device through [sim-use](https://github.com/lycorp-jp/sim-use) and offers Jev only part of
            what sim-use can do. Reading the screen, checking a result, single exact actions, and anything Jev is not offered
            are done with sim-use itself, either directly or through `jev-sim-use exec <sim-use args>`, which runs sim-use against
            the same device.

            sim-use's commands change between releases, so this skill does not describe them. Learn them from sim-use:

            - Install sim-use's own agent skill, which teaches its commands and is kept in step with the installed version. See
              `sim-use init --help` for how to install it for your client, and reinstall it after upgrading sim-use.
            - For any command, `sim-use --help` and `sim-use <command> --help` are the reference.

            Once the sim-use skill is installed, load it whenever a step needs sim-use directly, and use jev-sim-use for the
            multi-step navigation in between. A session's `resume` starts from whatever screen is showing, so fixing something
            by hand with sim-use and then continuing is fine.

            """#####,
        ),
        (
            "references/troubleshooting.md",
            #####"""
            # When a run stops: reading the cause

            Start from the step lines on stderr. Each shows the chosen action and its support, broken down by the answers it
            depends on, for example `support 0.49 [operation 0.97, element 0.49]`. The lowest number names what Jev was unsure
            about: the operation (what to do), the element (what to act on), the field, or the text. That tells you what a note
            or a fix has to supply.

            ## Causes seen most often

            **Low `element` on a row Jev clearly meant.** The row's title, its chevron, and its timestamp each get 0.4-0.55.
            The app exposes the row as separate text and image pieces instead of one button (typically a SwiftUI
            `onTapGesture` on a stack), so Jev splits its choice among them. `tell` which row opens the item, or tap it with
            `exec`. The lasting fix is in the app: give tappable rows and cells `.accessibilityElement(children: .combine)` (or
            `.ignore` with a label) and `.accessibilityAddTraits(.isButton)`.

            **Jev picks a real button (an Add menu) over the item you meant.** The item has no button trait, so it reads as
            plain text while the menu reads as an action. Same fix as above. If the item is already a button, the goal's wording
            is steering Jev: "post a record for X" can read as "add", so name the item you want opened.

            **Two controls whose labels look alike** (an AI rewrite and a plain Edit). Jev may take the wrong one, and an AI
            feature may receive your text as an instruction. Make the labels distinct in the app, and give each an
            `accessibilityHint` that says what it does. When Jev would otherwise hand over, jev-sim-use asks once more with the
            screen's hints ("asking again with the screen's accessibility hints" in the step lines).

            **A slider labelled with a number.** The slider has no accessibility label, so its label is its raw position.
            jev-sim-use names it from the text above it, but sim-use drags do not move SwiftUI sliders; set it by hand. App fix:
            `Slider(...) { Text("…") }` plus an `.accessibilityValue` with the displayed value and unit.

            **Something visible that the screen reading does not list.** A system prompt from another process (a password-save
            alert), most cells of a colour grid, a popover's close button. Take a screenshot with sim-use and act on it by
            coordinates, as its skill describes.

            **A tap that changes nothing on a row that opens a sheet or a picker.** Some controls ignore an instant tap. Tap it
            with sim-use using a short hold (see its skill for how).

            **Place words** ("home", "settings", "search", "back"). Jev reads them as the app's own first (a tab, screen, or
            button by that name) and as the device's only when the app has none. Say "the device's Home Screen" if you mean to
            leave the app; sim-use cannot open it again.

            **Creating something.** Say "and save it". Typed text is not saved, and Jev does not treat it as done.

            **Search.** A search field that acts on Return is fine; Jev can press Return. A results screen without a heading
            often ends as "probably reached"; read the screen to confirm.

            **Slow submits.** After an action that changes nothing, the run keeps reading for up to 2 s. A sign-up or save that
            takes longer can be pressed twice; check the result before resuming.

            **Interruptions.** Rating requests, tracking prompts, notification permission, password-save alerts, and promo
            banners can appear seconds after launch and derail a run midway. Clear them before starting, and after launching
            an app give it a few seconds before the first run.

            """#####,
        ),
    ]
}
