import Foundation

// Usage: EmbedSkillTool <output.swift> <skill directory> <file>...
// Writes `SkillBundle.files`: each file, in the order given, as a raw string literal whose contents are the file's
// bytes. The closing delimiter sits at column 0, so no indentation is stripped, and the line break before it is not
// part of the string, which is why one is always added after the file's own text.

let delimiter = "#####"
let arguments = CommandLine.arguments.dropFirst()
guard arguments.count >= 3, let outputPath = arguments.first else {
    FileHandle.standardError.write(Data("usage: EmbedSkillTool <output.swift> <skill directory> <file>...\n".utf8))
    exit(64)
}

let skill = URL(filePath: arguments.dropFirst().first ?? "")
var source = """
// Generated by the EmbedSkill build plugin from skills/jev-sim-use. Do not edit.

extension SkillBundle {
    /// Every file of skills/jev-sim-use, by its path inside the skill directory; SKILL.md comes first.
    static let files: [(path: String, contents: String)] = [

"""
for path in arguments.dropFirst(2) {
    let file = skill.appending(path: path)
    let contents = try String(contentsOf: file, encoding: .utf8)
    // Either would end the literal early or start an interpolation inside it.
    for terminator in ["\"\"\"" + delimiter, "\\" + delimiter] where contents.contains(terminator) {
        FileHandle.standardError.write(Data(
            "\(file.path()): error: contains `\(terminator)`, which the embedded raw string cannot hold; raise the # count in EmbedSkillTool\n".utf8,
        ))
        exit(1)
    }
    source += "        (\"\(path)\", \(delimiter)\"\"\"\n\(contents)\n\"\"\"\(delimiter)),\n"
}

source += "    ]\n}\n"
try source.write(to: URL(filePath: outputPath), atomically: true, encoding: .utf8)
