#!/bin/bash
# Embeds skills/jev-sim-use (SKILL.md and references/*.md) into the binary, because releases ship the executable
# alone (no SwiftPM resource bundle). SkillBundleDriftTests fails when this output is stale.
set -euo pipefail

root="$(cd "$(dirname "$0")/.." && pwd)"
skill="$root/skills/jev-sim-use"
output="$root/Sources/JevSimUseKit/Skill/SkillBundle+Generated.swift"

# SKILL.md first, then references in a stable order.
files=("SKILL.md")
if [ -d "$skill/references" ]; then
    while IFS= read -r file; do files+=("references/$(basename "$file")"); done < <(find "$skill/references" -maxdepth 1 -name '*.md' | sort)
fi

for file in "${files[@]}"; do
    if grep -q '"""#####' "$skill/$file"; then
        echo "error: $skill/$file contains the raw-string terminator; raise the # count in $0" >&2
        exit 1
    fi
done

{
    echo "// Generated by \`mise run generate-skill\` from skills/jev-sim-use. Do not edit."
    echo ""
    echo "extension SkillBundle {"
    echo "    /// Every file of skills/jev-sim-use, by its path inside the skill directory; SKILL.md comes first."
    echo "    static let files: [(path: String, contents: String)] = ["
    for file in "${files[@]}"; do
        echo "        ("
        echo "            \"$file\","
        echo "            #####\"\"\""
        # Indented the way SwiftFormat leaves it; the closing delimiter's indentation is stripped.
        sed 's/^./            &/' "$skill/$file"
        echo ""
        echo "            \"\"\"#####,"
        echo "        ),"
    done
    echo "    ]"
    echo "}"
} > "$output"
