#!/bin/bash
# Embeds skills/jev-sim-use/SKILL.md into the binary, because releases ship the executable alone
# (no SwiftPM resource bundle). SkillBundleDriftTests fails when this output is stale.
set -euo pipefail

root="$(cd "$(dirname "$0")/.." && pwd)"
source="$root/skills/jev-sim-use/SKILL.md"
output="$root/Sources/JevSimUseKit/Skill/SkillBundle+Generated.swift"

if grep -q '"""#####' "$source"; then
    echo "error: $source contains the raw-string terminator; raise the # count in $0" >&2
    exit 1
fi

{
    echo "// Generated by \`mise run generate-skill\` from skills/jev-sim-use/SKILL.md. Do not edit."
    echo ""
    echo "extension SkillBundle {"
    echo "    /// The contents of skills/jev-sim-use/SKILL.md."
    echo "    static let markdown = #####\"\"\""
    # Indented the way SwiftFormat leaves it; the closing delimiter's indentation is stripped.
    sed 's/^./    &/' "$source"
    echo ""
    echo "    \"\"\"#####"
    echo "}"
} > "$output"
